# Assignment 3

### Questions 1:
### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [5]:
#solution
arr=np.arange(2,51,3) #numpy array
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

### Questions 2:
### Accept two lists of 5 elements each from the user.Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [13]:
#solution

list1=[] #empty list 1
for i in range(0,5):
    n1=int(input()) #take the input values for list 1
    list1.append(n1)

list2=[] #empty list 1
for j in range(0,5):
    n2=int(input()) #take the input values for list 1
    list2.append(n2)

#convert them into numpy arrays
np_arr1=np.array(list1)
np_arr2=np.array(list2)

#concatenate these arrays
concat_arr=np.concatenate((np_arr1,np_arr2),axis=0)
print(concat_arr)

#sort these arrays
sort_arr1=np.sort(np_arr1)
print(sort_arr1)
sort_arr2=np.sort(np_arr2)
print(sort_arr2)

10
5
8
1
9
2
7
3
9
11
[10  5  8  1  9  2  7  3  9 11]
[ 1  5  8  9 10]
[ 2  3  7  9 11]


## Questions 3:
### Write a code snippet to find the dimensions of a ndarray and its size.

In [20]:
#solution

arr_1=np.array([4,6,7,8,9,2]) #numpy array
print(arr_1.ndim) #print the dimensions
print(arr_1.size) #print the size

arr_2=np.array([[6,8,3,1,9],[5,7,8,3,5]]) #numpy array
print(arr_2.ndim) #print the dimensions
print(arr_2.size) #print the size

1
6
2
10


### Questions 4:
### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet.
Hint: np.newaxis, np.expand_dims

In [31]:
#solution

x = np.array([5,1,2,7,8]) #numpy array
print(x.ndim) #print the dimension of x array
print(x.shape)

#by using np.newaxis
new_arr= x[np.newaxis, :] #convert 1D array into 2D array
print(new_arr.ndim) #print the dimension of new array
print(new_arr.shape)

1
(5,)
2
(1, 5)


In [34]:
#by using np.expand_dims
y = np.expand_dims(x, axis=0) #convert 1D array into 2D array
print(y.ndim) #print the dimension of new array
print(y.shape)

2
(1, 5)


### Questions 5:
### Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [38]:
#solution

a = np.array([[1, 2],[3, 4]]) 
b = np.array([[5, 6],[7, 8]]) 

# vertical stacking 
print(np.vstack((a, b))) 
print("\n")
# horizontal stacking 
print(np.hstack((a, b))) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


### Questions 6:
### How to get unique items and counts of unique items?

In [46]:
#solution

a=np.array([2,5,8,4,5,2,5,8,1,3,9]) #numpy array
print(np.unique(a)) #print unique values of numpy array

counts_items = np.unique(a, return_counts=True) #get unique items and counts of unique items
print(counts_items)

[1 2 3 4 5 8 9]
(array([1, 2, 3, 4, 5, 8, 9]), array([1, 2, 1, 1, 3, 2, 1], dtype=int64))
